<form action="<?php echo $block->getFormAction() ?>" method="post" class="wholesale-registration-form">
    <div class="wholesale_registration row">
    <div class="col-sm-6">
        <label for="firstname">First Name: required</label><input name="firstname" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="lastname">Last Name: required </label><input name="lastname" type="text" required>
    </div>
    <div class="col-sm-12">
        <label for="address1">Address 1: required</label><input name="address1" type="text" required>
    </div>
    <div class="col-sm-12">
        <label for="address2">Address 2:</label><input name="address2" type="text">
    </div>
    <div class="col-sm-4">
        <label for="city">City: required</label><input name="city" type="text" required>
    </div>
    <div class="col-sm-4">
        <label for="state">State: required</label>
        <select name="state" required>
            <option value="" selected="selected"> - Please Select - </option>
            <option value="AB">Alberta</option>
            <option value="BC">British Columbia</option>
            <option value="MB">Manitoba</option>
            <option value="NB">New Brunswick</option>
            <option value="NL">Newfoundland and Labrador</option>
            <option value="NS">Nova Scotia</option>
            <option value="NT">Northwest Territories</option>
            <option value="NU">Nunavut</option>
            <option value="ON">Ontario</option>
            <option value="PE">Prince Edward Island</option>
            <option value="QC">Quebec</option>
            <option value="SK">Saskatchewan</option>
            <option value="YT">Yukon</option>
            <option value=""> - States - </option>
            <option value="AL">Alabama</option>
            <option value="AK">Alaska</option>
            <option value="AZ">Arizona</option>
            <option value="AR">Arkansas</option>
            <option value="CA">California</option>
            <option value="CO">Colorado</option>
            <option value="CT">Connecticut</option>
            <option value="DE">Delaware</option>
            <option value="DC">District Of Columbia</option>
            <option value="FL">Florida</option>
            <option value="GA">Georgia</option>
            <option value="HI">Hawaii</option>
            <option value="ID">Idaho</option>
            <option value="IL">Illinois</option>
            <option value="IN">Indiana</option>
            <option value="IA">Iowa</option>
            <option value="KS">Kansas</option>
            <option value="KY">Kentucky</option>
            <option value="LA">Louisiana</option>
            <option value="ME">Maine</option>
            <option value="MD">Maryland</option>
            <option value="MA">Massachusetts</option>
            <option value="MI">Michigan</option>
            <option value="MN">Minnesota</option>
            <option value="MS">Mississippi</option>
            <option value="MO">Missouri</option>
            <option value="MT">Montana</option>
            <option value="NE">Nebraska</option>
            <option value="NV">Nevada</option>
            <option value="NH">New Hampshire</option>
            <option value="NJ">New Jersey</option>
            <option value="NM">New Mexico</option>
            <option value="NY">New York</option>
            <option value="NC">North Carolina</option>
            <option value="ND">North Dakota</option>
            <option value="OH">Ohio</option>
            <option value="OK">Oklahoma</option>
            <option value="OR">Oregon</option>
            <option value="PA">Pennsylvania</option>
            <option value="RI">Rhode Island</option>
            <option value="SC">South Carolina</option>
            <option value="SD">South Dakota</option>
            <option value="TN">Tennessee</option>
            <option value="TX">Texas</option>
            <option value="UT">Utah</option>
            <option value="VT">Vermont</option>
            <option value="VA">Virginia</option>
            <option value="WA">Washington</option>
            <option value="WV">West Virginia</option>
            <option value="WI">Wisconsin</option>
            <option value="WY">Wyoming</option>
        </select>
    </div>
    <div class="col-sm-4">
        <label for="zipcode">ZIP Code: required</label><input name="zipcode" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="phone">Daytime Phone: required</label><input name="phone" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="email">Email: required </label><input name="email" type="email" required>
    </div>

    <div class="col-sm-6">
        <label for="company">Company Name: required</label><input name="company" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="companyalt">Company Alt Name or DBA</label><input name="companyalt" type="text">
    </div>
    <div class="col-sm-6">
        <label for="ein">EIN (Employer Identification Number): required</label><input name="ein" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="geo">Business Geographic Region: required</label>
        <div class="col-sm-6"><input type="checkbox" name="geo[]" value="Northeast"> Northeast</div>
        <div class="col-sm-6"><input type="checkbox" name="geo[]" value="South"> South</div>
        <div class="col-sm-6"><input type="checkbox" name="geo[]" value="Midwest"> Midwest</div>
        <div class="col-sm-6"><input type="checkbox" name="geo[]" value="West"> West</div>
      </div>
    <div class="col-sm-6">
        <label for="revenue">What is your annual revenue?: required</label><input name="revenue" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="numberofyears">Number of years operating: required</label><input name="numberofyears" type="text" required>
    </div>
    <div class="col-sm-6">
        <label for="howdidyouhear">How did you hear about us?: required</label>
        <select name="howdidyouhear" required>
            <option value="" selected="selected"> - Please Select - </option>
            <option value="Online Search">Online Search</option>
            <option value="Referral">Referral</option>
            <option value="Tradeshow">Tradeshow</option>
            <option value="Magazine Ad">Magazine Ad</option>
            <option value="Instagram">Instagram</option>
            <option value="Pinterest">Pinterest</option>
            <option value="Facebook">Facebook</option>
            <option value="Linkedin">Linkedin</option>
        </select>
    </div>
    <div class="col-sm-6">
        <label for="decor">Describe your decor style: required</label>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Casual"> Casual</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Urban Chic"> Urban Chic</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Contemporary"> Contemporary</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Rustic"> Rustic</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Traditional"> Traditional</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Coastal"> Coastal</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Country"> Country</div>
        <div class="col-sm-6"><input type="checkbox" name="decor[]" value="Formal"> Formal</div>
    </div>

    <input type="submit" class="register" value="Register">
    </div>
</form>